In [3]:
import pandas as pd

Maak lijst met alle proprerty elements

In [8]:
file_name = "Relations"
path = f"tests/unit/fixtures/test_transformer/{file_name}.parquet"
Relations = pd.read_parquet(path)

Relations

,Relation,Cardinality,RelationID,R2Element,R2ElementID
0,[WEG] Heeft,0:n,70d4bcc7-f731-e911-a2d5-00155d641103,[WEG] Commentaar OG,bd935484-852f-e911-a2d5-00155d641103
1,[WEG] Heeft,1:1,2b36157b-0239-e911-a2d7-00155d641104,[WEG] Interpretatie OG,e7966525-0239-e911-a2d7-00155d641104
2,[WEG] Heeft property,0:1,28e40114-69d5-ea11-a2f0-00155d641104,[WEG] SRA status ON,7a4ae8fe-68d5-ea11-a2f0-00155d641104
3,[WEG] Heeft property,0:1,caf5f4e1-68d5-ea11-a2f0-00155d641104,[WEG] SMART-analyse OG,3d39b0b0-68d5-ea11-a2f0-00155d641104
4,[WEG] Heeft voorgestelde,0:1,75edf1cc-7754-e911-a2d8-00155d641103,[WEG] Commentaar OG,bd935484-852f-e911-a2d5-00155d641103
5,Bevat (S),0:n,1731cf9e-0239-e911-a2d7-00155d641104,Eis,4dfa1495-7a2f-e911-a2d5-00155d641103
6,Heeft,0:1,e1ecc874-0759-ee11-b6a0-001dd8d702bf,Honorering,2d821dd9-0259-ee11-b6a0-001dd8d702bf
7,Heeft,0:n,1a160899-b699-ea11-a2ec-00155d641103,Toelichting,ae962581-b699-ea11-a2ec-00155d641103
8,Heeft,0:n,73d4bcc7-f731-e911-a2d5-00155d641103,Commentaar,275a8d8a-852f-e911-a2d5-00155d641103
9,Heeft,0:n,924d97e4-f731-e911-a2d5-00155d641103,Verificatievoorschrift,7be9db74-892f-e911-a2d5-00155d641103
10,Heeft,0:n,a04f7a89-e69b-e911-a2df-00155d641103,Gezamenlijke toelichting ON,eff6f051-e69b-e911-a2df-00155d641103
11,Heeft,0:n,dbedf7db-f731-e911-a2d5-00155d641103,[WEG] Verificatiecommentaar OG,37be0968-892f-e911-a2d5-00155d641103
12,Heeft,0:n,e0045d83-e69b-e911-a2df-00155d641103,Gezamenlijke toelichting OG,74cdf44a-e69b-e911-a2df-00155d641103
13,Heeft,1:1,2836157b-0239-e911-a2d7-00155d641104,Interpretatie ON,5046ad2b-0239-e911-a2d7-00155d641104
14,Heeft,1:1,877b33d5-f731-e911-a2d5-00155d641103,Project Activiteit,7efa7ec2-7a2f-e911-a2d5-00155d641103
15,Heeft,1:n,a06a34ce-f731-e911-a2d5-00155d641103,Eistekst,1979f387-862f-e911-a2d5-00155d641103
16,Heeft (C),0:n,8ef67718-59b9-eb11-b678-001dd8d702bc,Eis,4dfa1495-7a2f-e911-a2d5-00155d641103
17,Heeft betrekking op,0:n,7cc6e1a5-5af4-ef11-b6be-001dd8d702bf,GRIP Item,026357e7-48f4-ef11-b6be-001dd8d702bf
18,Heeft betrekking op,0:n,8becad86-f731-e911-a2d5-00155d641103,Aspect,892943cc-9b2e-e911-a2d5-00155d641103
19,Heeft betrekking op,0:n,c2376eb1-f731-e911-a2d5-00155d641103,Technologie/Principe,25a6f138-892f-e911-a2d5-00155d641103
20,Heeft betrekking op Activiteit,0:n,fa588c88-f931-e911-a2d5-00155d641103,ME-Eis-Activiteit,79aa8f8f-862f-e911-a2d5-00155d641103
21,Heeft betrekking op Bedrijfsproces,0:n,6ba4b8d6-148f-ec11-b687-001dd8d702bc,ME-Eis-Bedrijfsproces,d0e1e0ab-148f-ec11-b687-001dd8d702bc
22,Heeft betrekking op EOS Apparaat,0:n,8bf0914f-1e04-ec11-b67d-001dd8d702bc,ME-Eis-EOS apparaat,de60ade4-1d04-ec11-b67d-001dd8d702bc
23,Heeft betrekking op SBS,0:n,f6588c88-f931-e911-a2d5-00155d641103,ME-Eis-SBS,32b16920-832f-e911-a2d5-00155d641103
24,Heeft betrekking op SBS Contract,0:n,7e073d44-7637-ef11-b6ae-001dd8d702bf,ME-Eis-SBS Contract,c5cfa4b7-95f9-43f1-841d-f58e00c8cd5a
25,Heeft betrekking op SBS Type,0:n,b121dda7-77c1-ec11-b689-001dd8d702bf,ME-Eis-SBS type,5371c67e-77c1-ec11-b689-001dd8d702bf
26,Heeft contactpersoon,0:1,79a4f66f-efa6-e911-a2df-00155d641103,Rol,48e2234a-9b2e-e911-a2d5-00155d641103
27,Heeft eigenaar,0:n,d8af7d26-f931-e911-a2d5-00155d641103,Rol,48e2234a-9b2e-e911-a2d5-00155d641103
28,Heeft property,0:1,108e6382-9747-f011-b6c2-001dd8d702bc,SRA Thema,fe4a0331-9547-f011-b6c2-001dd8d702bc
29,Heeft property,0:1,25e40114-69d5-ea11-a2f0-00155d641104,SMART-analyse,9dc8ef06-69d5-ea11-a2f0-00155d641104
30,Heeft property,0:1,44b531ee-9aae-ec11-b688-001dd8d702bf,Type,fa7e60d4-9aae-ec11-b688-001dd8d702bf
31,Heeft property,0:1,458f8a61-75f5-e911-a2e5-00155d641104,Geldig tot en met,2ecb4ecc-d1f4-e911-a2e5-00155d641104
32,Heeft property,0:1,488f8a61-75f5-e911-a2e5-00155d641104,Geldig vanaf,8f4ecdda-d1f4-e911-a2e5-00155d641104
33,Heeft property,0:1,8b045c3a-75f5-e911-a2e5-00155d641104,RI&E opvolging,34ac2ae8-d1f4-e911-a2e5-00155d641104
34,Heeft property,0:1,a68e3dcd-f092-eb11-b674-001dd8d702bc,EMVI kans,93790c78-f092-eb11-b674-001dd8d702bc
35,Heeft property,0:1,ab8e3dcd-f092-eb11-b674-001dd8d702bc,Financieel risico,7860baa1-f092-eb11-b674-001dd8d702bc
36,Heeft property,0:1,c98e3dcd-f092-eb11-b674-001dd8d702bc,Kans,2960baa1-f092-eb11-b674-001dd8d702bc
37,Heeft property,0:1,d28e3dcd-f092-eb11-b674-001dd8d702bc,Risico,df58619a-f092-eb11-b674-001dd8d702bc
38,Heeft property,0:1,ee82d201-0759-ee11-b6a0-001dd8d702bf,Thema,c36b197e-0259-ee11-b6a0-001dd8d702bf
39,Heeft property,0:1,f8afd577-ff12-f111-b6cd-001dd8d702bf,Contractfase,5e06a84f-ff12-f111-b6cd-001dd8d702bf
40,Heeft property,0:1,fe161de8-68d5-ea11-a2f0-00155d641104,SRA status,8c35dcb7-68d5-ea11-a2f0-00155d641104
41,Heeft property,0:1|1,04171de8-68d5-ea11-a2f0-00155d641104,Status,fb1e21be-68d5-ea11-a2f0-00155d641104
42,Heeft property,0:1|1,83194cdb-68d5-ea11-a2f0-00155d641104,Geaccepteerd door ON,70b59d6a-68d5-ea11-a2f0-00155d641104
43,Heeft voorgestelde,0:n,49fc8e7a-f831-e911-a2d5-00155d641103,ME-Eis-Discipline mutatie,70dbef1c-862f-e911-a2d5-00155d641103
44,Is beschreven in,0:n,2033ca8e-f831-e911-a2d5-00155d641103,Document,b940cb29-7a2f-e911-a2d5-00155d641103
45,Is geinitieerd door,0:1,796a34bb-f831-e911-a2d5-00155d641103,Bedrijf,c1fe1b6a-9b2e-e911-a2d5-00155d641103
46,Is geinitieerd door,0:1,851831a6-309b-ee11-b6a6-001dd8d702bf,Persoon,fb5daf56-9b2e-e911-a2d5-00155d641103
47,Is van type,0:n,aea5f7a4-f831-e911-a2d5-00155d641103,Eis onderwerp,0e33f280-862f-e911-a2d5-00155d641103
48,Leidt tot,0:n,90db2205-e5ae-e911-a2df-00155d641103,Issue,315f53aa-7b2f-e911-a2d5-00155d641103
49,Resulteert in,0:n,8aa9d278-3eca-e911-a2e4-00155d641104,Ontwerp besluit,69bcbc50-39ca-e911-a2e4-00155d641104

In [95]:
prop_relations = Relations[~Relations['Relation'].str.contains('Heeft property', na=False)]
prop_relations = prop_relations[(prop_relations['Cardinality'] == '0:1') | (prop_relations['Cardinality'] == '1:1')]
prop_relations.to_csv()

',Relation,Cardinality,RelationID,R2Element,R2ElementID\n1,[WEG] Heeft,1:1,2b36157b-0239-e911-a2d7-00155d641104,[WEG] Interpretatie OG,e7966525-0239-e911-a2d7-00155d641104\n4,[WEG] Heeft voorgestelde,0:1,75edf1cc-7754-e911-a2d8-00155d641103,[WEG] Commentaar OG,bd935484-852f-e911-a2d5-00155d641103\n6,Heeft,0:1,e1ecc874-0759-ee11-b6a0-001dd8d702bf,Honorering,2d821dd9-0259-ee11-b6a0-001dd8d702bf\n13,Heeft,1:1,2836157b-0239-e911-a2d7-00155d641104,Interpretatie ON,5046ad2b-0239-e911-a2d7-00155d641104\n14,Heeft,1:1,877b33d5-f731-e911-a2d5-00155d641103,Project Activiteit,7efa7ec2-7a2f-e911-a2d5-00155d641103\n26,Heeft contactpersoon,0:1,79a4f66f-efa6-e911-a2df-00155d641103,Rol,48e2234a-9b2e-e911-a2d5-00155d641103\n45,Is geinitieerd door,0:1,796a34bb-f831-e911-a2d5-00155d641103,Bedrijf,c1fe1b6a-9b2e-e911-a2d5-00155d641103\n46,Is geinitieerd door,0:1,851831a6-309b-ee11-b6a6-001dd8d702bf,Persoon,fb5daf56-9b2e-e911-a2d5-00155d641103\n'

In [116]:
file_name = "RelationInstances"
path = f"tests/unit/fixtures/test_transformer/{file_name}.parquet"
RelationInstances = pd.read_parquet(path)
# RelationInstances.head(5).to_dict()

In [114]:
prop_relations_elements = RelationInstances[RelationInstances['RelationID'].isin(prop_relations['RelationID'])]
prop_relations_elements = prop_relations_elements.reset_index(drop=True)
prop_relations_elements

,R1Instance,R1InstanceID,RelationInstanceID,R2Instance,R2InstanceID,R2Element,Cardinality,RelationID,R1Element
0,AB010,cb14a391-7f6e-ee11-b6a1-001dd8d702bc,0615a391-7f6e-ee11-b6a1-001dd8d702bc,Interpretatie OG,0415a391-7f6e-ee11-b6a1-001dd8d702bc,[WEG] Interpretatie OG,1:1,2b36157b-0239-e911-a2d7-00155d641104,Eis
1,AB010,cb14a391-7f6e-ee11-b6a1-001dd8d702bc,f914a391-7f6e-ee11-b6a1-001dd8d702bc,Project Activiteit,f114a391-7f6e-ee11-b6a1-001dd8d702bc,Project Activiteit,1:1,877b33d5-f731-e911-a2d5-00155d641103,Eis
2,AB010,cb14a391-7f6e-ee11-b6a1-001dd8d702bc,fe14a391-7f6e-ee11-b6a1-001dd8d702bc,Interpretatie ON,fc14a391-7f6e-ee11-b6a1-001dd8d702bc,Interpretatie ON,1:1,2836157b-0239-e911-a2d7-00155d641104,Eis
3,AB100,f0ed48e5-7f6e-ee11-b6a1-001dd8d702bc,26ee48e5-7f6e-ee11-b6a1-001dd8d702bc,Project Activiteit,1dee48e5-7f6e-ee11-b6a1-001dd8d702bc,Project Activiteit,1:1,877b33d5-f731-e911-a2d5-00155d641103,Eis
4,AB100,f0ed48e5-7f6e-ee11-b6a1-001dd8d702bc,2aee48e5-7f6e-ee11-b6a1-001dd8d702bc,Interpretatie ON,28ee48e5-7f6e-ee11-b6a1-001dd8d702bc,Interpretatie ON,1:1,2836157b-0239-e911-a2d7-00155d641104,Eis
5,AB100,f0ed48e5-7f6e-ee11-b6a1-001dd8d702bc,33ee48e5-7f6e-ee11-b6a1-001dd8d702bc,Interpretatie OG,31ee48e5-7f6e-ee11-b6a1-001dd8d702bc,[WEG] Interpretatie OG,1:1,2b36157b-0239-e911-a2d7-00155d641104,Eis
6,AB110,4ab472c1-7f6e-ee11-b6a1-001dd8d702bc,ab5869c7-7f6e-ee11-b6a1-001dd8d702bc,Project Activiteit,a25869c7-7f6e-ee11-b6a1-001dd8d702bc,Project Activiteit,1:1,877b33d5-f731-e911-a2d5-00155d641103,Eis
7,AB110,4ab472c1-7f6e-ee11-b6a1-001dd8d702bc,af5869c7-7f6e-ee11-b6a1-001dd8d702bc,Interpretatie ON,ad5869c7-7f6e-ee11-b6a1-001dd8d702bc,Interpretatie ON,1:1,2836157b-0239-e911-a2d7-00155d641104,Eis
8,AB110,4ab472c1-7f6e-ee11-b6a1-001dd8d702bc,b85869c7-7f6e-ee11-b6a1-001dd8d702bc,Interpretatie OG,b65869c7-7f6e-ee11-b6a1-001dd8d702bc,[WEG] Interpretatie OG,1:1,2b36157b-0239-e911-a2d7-00155d641104,Eis

Nu heb je de property elementen als R2Instance en de R1instanceID. Nu moet dit een wide tabel worden. R1instanceID als index, alle R2Elements als colommen en R2instance als waarde van deze kolommen

In [109]:
# prop_relations_elements.pivot(index='R1InstanceID', columns='R2Element', values='R2InstanceID').reindex(columns=prop_relations['R2Element']).rename_axis(columns=None)
prop_relations_elements

,R1Instance,R1InstanceID,RelationInstanceID,R2Instance,R2InstanceID,R2Element,Cardinality,RelationID,R1Element
0,AB010,cb14a391-7f6e-ee11-b6a1-001dd8d702bc,0615a391-7f6e-ee11-b6a1-001dd8d702bc,Interpretatie OG,0415a391-7f6e-ee11-b6a1-001dd8d702bc,[WEG] Interpretatie OG,1:1,2b36157b-0239-e911-a2d7-00155d641104,Eis
1,AB010,cb14a391-7f6e-ee11-b6a1-001dd8d702bc,f914a391-7f6e-ee11-b6a1-001dd8d702bc,Project Activiteit,f114a391-7f6e-ee11-b6a1-001dd8d702bc,Project Activiteit,1:1,877b33d5-f731-e911-a2d5-00155d641103,Eis
2,AB010,cb14a391-7f6e-ee11-b6a1-001dd8d702bc,fe14a391-7f6e-ee11-b6a1-001dd8d702bc,Interpretatie ON,fc14a391-7f6e-ee11-b6a1-001dd8d702bc,Interpretatie ON,1:1,2836157b-0239-e911-a2d7-00155d641104,Eis
3,AB100,f0ed48e5-7f6e-ee11-b6a1-001dd8d702bc,26ee48e5-7f6e-ee11-b6a1-001dd8d702bc,Project Activiteit,1dee48e5-7f6e-ee11-b6a1-001dd8d702bc,Project Activiteit,1:1,877b33d5-f731-e911-a2d5-00155d641103,Eis
4,AB100,f0ed48e5-7f6e-ee11-b6a1-001dd8d702bc,2aee48e5-7f6e-ee11-b6a1-001dd8d702bc,Interpretatie ON,28ee48e5-7f6e-ee11-b6a1-001dd8d702bc,Interpretatie ON,1:1,2836157b-0239-e911-a2d7-00155d641104,Eis
5,AB100,f0ed48e5-7f6e-ee11-b6a1-001dd8d702bc,33ee48e5-7f6e-ee11-b6a1-001dd8d702bc,Interpretatie OG,31ee48e5-7f6e-ee11-b6a1-001dd8d702bc,[WEG] Interpretatie OG,1:1,2b36157b-0239-e911-a2d7-00155d641104,Eis
6,AB110,4ab472c1-7f6e-ee11-b6a1-001dd8d702bc,ab5869c7-7f6e-ee11-b6a1-001dd8d702bc,Project Activiteit,a25869c7-7f6e-ee11-b6a1-001dd8d702bc,Project Activiteit,1:1,877b33d5-f731-e911-a2d5-00155d641103,Eis
7,AB110,4ab472c1-7f6e-ee11-b6a1-001dd8d702bc,af5869c7-7f6e-ee11-b6a1-001dd8d702bc,Interpretatie ON,ad5869c7-7f6e-ee11-b6a1-001dd8d702bc,Interpretatie ON,1:1,2836157b-0239-e911-a2d7-00155d641104,Eis
8,AB110,4ab472c1-7f6e-ee11-b6a1-001dd8d702bc,b85869c7-7f6e-ee11-b6a1-001dd8d702bc,Interpretatie OG,b65869c7-7f6e-ee11-b6a1-001dd8d702bc,[WEG] Interpretatie OG,1:1,2b36157b-0239-e911-a2d7-00155d641104,Eis

In [115]:
relations = Relations.copy()
n_relationids_per_element = Relations.groupby('R2Element')['RelationID'].transform('nunique')
needs_prefix = n_relationids_per_element > 1
relations['R2Element_resolved'] = relations['R2Element'] + "_guid"
relations.loc[needs_prefix, 'R2Element_resolved'] = (
    relations.loc[needs_prefix, 'Relation'] + '_' + relations.loc[needs_prefix, 'R2Element']
)
relation_id_to_resolved = relations.set_index('RelationID')['R2Element_resolved'].to_dict()
prop_relations_elements['R2Cleaned'] = prop_relations_elements['RelationID'].map(relation_id_to_resolved)
prop_relations_elements

,R1Instance,R1InstanceID,RelationInstanceID,R2Instance,R2InstanceID,R2Element,Cardinality,RelationID,R1Element,R2Cleaned
0,AB010,cb14a391-7f6e-ee11-b6a1-001dd8d702bc,0615a391-7f6e-ee11-b6a1-001dd8d702bc,Interpretatie OG,0415a391-7f6e-ee11-b6a1-001dd8d702bc,[WEG] Interpretatie OG,1:1,2b36157b-0239-e911-a2d7-00155d641104,Eis,[WEG] Interpretatie OG_guid
1,AB010,cb14a391-7f6e-ee11-b6a1-001dd8d702bc,f914a391-7f6e-ee11-b6a1-001dd8d702bc,Project Activiteit,f114a391-7f6e-ee11-b6a1-001dd8d702bc,Project Activiteit,1:1,877b33d5-f731-e911-a2d5-00155d641103,Eis,Project Activiteit_guid
2,AB010,cb14a391-7f6e-ee11-b6a1-001dd8d702bc,fe14a391-7f6e-ee11-b6a1-001dd8d702bc,Interpretatie ON,fc14a391-7f6e-ee11-b6a1-001dd8d702bc,Interpretatie ON,1:1,2836157b-0239-e911-a2d7-00155d641104,Eis,Interpretatie ON_guid
3,AB100,f0ed48e5-7f6e-ee11-b6a1-001dd8d702bc,26ee48e5-7f6e-ee11-b6a1-001dd8d702bc,Project Activiteit,1dee48e5-7f6e-ee11-b6a1-001dd8d702bc,Project Activiteit,1:1,877b33d5-f731-e911-a2d5-00155d641103,Eis,Project Activiteit_guid
4,AB100,f0ed48e5-7f6e-ee11-b6a1-001dd8d702bc,2aee48e5-7f6e-ee11-b6a1-001dd8d702bc,Interpretatie ON,28ee48e5-7f6e-ee11-b6a1-001dd8d702bc,Interpretatie ON,1:1,2836157b-0239-e911-a2d7-00155d641104,Eis,Interpretatie ON_guid
5,AB100,f0ed48e5-7f6e-ee11-b6a1-001dd8d702bc,33ee48e5-7f6e-ee11-b6a1-001dd8d702bc,Interpretatie OG,31ee48e5-7f6e-ee11-b6a1-001dd8d702bc,[WEG] Interpretatie OG,1:1,2b36157b-0239-e911-a2d7-00155d641104,Eis,[WEG] Interpretatie OG_guid
6,AB110,4ab472c1-7f6e-ee11-b6a1-001dd8d702bc,ab5869c7-7f6e-ee11-b6a1-001dd8d702bc,Project Activiteit,a25869c7-7f6e-ee11-b6a1-001dd8d702bc,Project Activiteit,1:1,877b33d5-f731-e911-a2d5-00155d641103,Eis,Project Activiteit_guid
7,AB110,4ab472c1-7f6e-ee11-b6a1-001dd8d702bc,af5869c7-7f6e-ee11-b6a1-001dd8d702bc,Interpretatie ON,ad5869c7-7f6e-ee11-b6a1-001dd8d702bc,Interpretatie ON,1:1,2836157b-0239-e911-a2d7-00155d641104,Eis,Interpretatie ON_guid
8,AB110,4ab472c1-7f6e-ee11-b6a1-001dd8d702bc,b85869c7-7f6e-ee11-b6a1-001dd8d702bc,Interpretatie OG,b65869c7-7f6e-ee11-b6a1-001dd8d702bc,[WEG] Interpretatie OG,1:1,2b36157b-0239-e911-a2d7-00155d641104,Eis,[WEG] Interpretatie OG_guid

In [118]:
from typing import Literal
CARDINALITY_COL = "Cardinality"

def _filter_cardinality(
    df: pd.DataFrame,
    cardinality: Literal["many", "one"]
) -> pd.DataFrame:
    """
    Takes a Dataframe and filters on cardinality column
    based on cardinality argument it either filters :n caridinality
    or :1 cardinality
    """
    df[CARDINALITY_COL] = df[CARDINALITY_COL].map(
        lambda x: ":n" 
        if "n" in str(x).split(":")[-1]
        else ":1"
    ) 
    
    if cardinality == "many":
        return df[df[CARDINALITY_COL] == ":n"]
    
    else:
        return df[df[CARDINALITY_COL] == ":1"]

relations_df = Relations.copy()
relations_instances_df = RelationInstances.copy()


# Filter to only have :1 cardinality and not 'Heeft property' relations
relations = relations_df[~relations_df['Relation'].str.contains('Heeft property', na=False)]
relations = _filter_cardinality(df=relations, cardinality='one')

# Get a new column where you construct the column name used later. it's easier to do it here as to ensure all relations are always present.
# Check if a R2Element occurs multiple times, if yes add the relation name in front. if not do nothing. For both cases append_guid.

n_relationids_per_R2element = relations.groupby('R2Element')['RelationID'].transform('nunique')
needs_prefix = n_relationids_per_R2element > 1 # This is a mask to be used for later transformations.

relations['R2Element_resolved'] = relations['R2Element'] + "_guid"
# Use the mask created above to indentify the rows that need a prefix and add this prefix
relations.loc[needs_prefix, 'R2Element_resolved'] = (
    relations.loc[needs_prefix, 'Relation'] + '_' + relations.loc[needs_prefix, 'R2Element']
)
# Create the mapping for the element table for later, apply just before the pivot and use this column for the pivor instead of R2Element.
columnname_mapping_R2Element = relations.set_index('RelationID')['R2Element_resolved'].to_dict()

# Create dataframe with relation instances based on the mask generated above. This table now contains all to one relations that are not preperty elements.
relation_elements = relations_instances_df[relations_instances_df['RelationID'].isin(relations['RelationID'])]
relation_elements['R2Element_resolved'] = relation_elements['RelationID'].map(columnname_mapping_R2Element)
# Pivot so that the index is R1InstanceID and columns are the 
relation_elements = relation_elements.pivot(index='R1InstanceID', columns='R2Element_resolved', values='R2InstanceID').reindex(columns=relations['R2Element_resolved']).rename_axis(columns=None)
relation_elements

,[WEG] Interpretatie OG_guid,[WEG] Commentaar OG_guid,Honorering_guid,Interpretatie ON_guid,Project Activiteit_guid,Rol_guid,Bedrijf_guid,Persoon_guid
R1InstanceID,,,,,,,,
4ab472c1-7f6e-ee11-b6a1-001dd8d702bc,b65869c7-7f6e-ee11-b6a1-001dd8d702bc,NaN,NaN,ad5869c7-7f6e-ee11-b6a1-001dd8d702bc,a25869c7-7f6e-ee11-b6a1-001dd8d702bc,NaN,NaN,NaN
cb14a391-7f6e-ee11-b6a1-001dd8d702bc,0415a391-7f6e-ee11-b6a1-001dd8d702bc,NaN,NaN,fc14a391-7f6e-ee11-b6a1-001dd8d702bc,f114a391-7f6e-ee11-b6a1-001dd8d702bc,NaN,NaN,NaN
f0ed48e5-7f6e-ee11-b6a1-001dd8d702bc,31ee48e5-7f6e-ee11-b6a1-001dd8d702bc,NaN,NaN,28ee48e5-7f6e-ee11-b6a1-001dd8d702bc,1dee48e5-7f6e-ee11-b6a1-001dd8d702bc,NaN,NaN,NaN

In [6]:
file_name = "ElementInstances"
path = f"tests/unit/fixtures/test_transformer/{file_name}.parquet"
ElementInstances = pd.read_parquet(path)
# RelationInstances.head(5).to_dict()

In [7]:
ElementInstances

,R1Instance,R1InstanceDescription,R1InstanceID,R1InstanceRichText
0,AB010,Arbeidsvoorwaardelijke bepalingen,cb14a391-7f6e-ee11-b6a1-001dd8d702bc,NaN
1,AB100,Arbeidsvoorwaardelijke bepalingen,f0ed48e5-7f6e-ee11-b6a1-001dd8d702bc,NaN
2,AB110,Arbeidsvoorwaardelijke bepalingen,4ab472c1-7f6e-ee11-b6a1-001dd8d702bc,NaN
3,AB200,Arbeidsvoorwaardelijke bepalingen,5adf5bd3-7f6e-ee11-b6a1-001dd8d702bc,NaN
4,AB210,Arbeidsvoorwaardelijke bepalingen,ce4d8da9-7f6e-ee11-b6a1-001dd8d702bc,NaN
5,AB220,Arbeidsvoorwaardelijke bepalingen,f4de5bd3-7f6e-ee11-b6a1-001dd8d702bc,NaN
6,AB230,Arbeidsvoorwaardelijke bepalingen,e8bd9b97-7f6e-ee11-b6a1-001dd8d702bc,NaN
7,AB400,Arbeidsvoorwaardelijke bepalingen,189c79bb-7f6e-ee11-b6a1-001dd8d702bc,NaN
8,AB410,Arbeidsvoorwaardelijke bepalingen,d39979bb-7f6e-ee11-b6a1-001dd8d702bc,NaN
9,AB420,Arbeidsvoorwaardelijke bepalingen,fbbb9b97-7f6e-ee11-b6a1-001dd8d702bc,NaN
10,AB520,Arbeidsvoorwaardelijke bepalingen,93de5bd3-7f6e-ee11-b6a1-001dd8d702bc,NaN
11,AV010,Voldoen aan de Wet arbeid vreemdelingen,1ae05bd3-7f6e-ee11-b6a1-001dd8d702bc,NaN
12,B-AB300,Arbeidsvoorwaardelijke bepalingen,1ed53ef1-7f6e-ee11-b6a1-001dd8d702bc,NaN
13,B-AB500,Arbeidsvoorwaardelijke bepalingen,a6508da9-7f6e-ee11-b6a1-001dd8d702bc,NaN
14,B-AB510,Arbeidsvoorwaardelijke bepalingen,9d673feb-7f6e-ee11-b6a1-001dd8d702bc,NaN
15,BB010,bouwborden,bd5969c7-7f6e-ee11-b6a1-001dd8d702bc,NaN
16,B-BS330,Omgaan met en beperken van schade,c4d43ef1-7f6e-ee11-b6a1-001dd8d702bc,NaN
17,B-BS340,Omgaan met en beperken van schade,358564cd-7f6e-ee11-b6a1-001dd8d702bc,NaN
18,B-BS390,Omgaan met en beperken van schade,81e05bd3-7f6e-ee11-b6a1-001dd8d702bc,NaN
19,B-CD020,Communiceren met derden,b6bc9b97-7f6e-ee11-b6a1-001dd8d702bc,NaN
20,B-CD030,Communiceren met derden,6b4f8da9-7f6e-ee11-b6a1-001dd8d702bc,NaN
21,B-CO020,CO2 reductie,a713a391-7f6e-ee11-b6a1-001dd8d702bc,NaN
22,B-CS010,Coördinatie met SWM,f15e38f7-7f6e-ee11-b6a1-001dd8d702bc,NaN
23,B-CW010,Coördinatie van werkzaamheden,4b5c38f7-7f6e-ee11-b6a1-001dd8d702bc,NaN
24,B-CW080,Coördinatie van werkzaamheden,715d38f7-7f6e-ee11-b6a1-001dd8d702bc,NaN
25,B-FM020,Financieel management,adf7ad85-7f6e-ee11-b6a1-001dd8d702bc,NaN
26,B-FM030,Financieel management,53b99b97-7f6e-ee11-b6a1-001dd8d702bc,NaN
27,B-FM170,Financieel management,f703a78b-7f6e-ee11-b6a1-001dd8d702bc,NaN
28,B-FM190,Financieel management,1b127eb5-7f6e-ee11-b6a1-001dd8d702bc,NaN
29,B-FM195,Financieel management,f3b072c1-7f6e-ee11-b6a1-001dd8d702bc,NaN
30,B-FM300,Financieel management,2b5187af-7f6e-ee11-b6a1-001dd8d702bc,NaN
31,B-FM310,Financieel management,31b072c1-7f6e-ee11-b6a1-001dd8d702bc,NaN
32,B-FM320,Financieel management,936d55d9-7f6e-ee11-b6a1-001dd8d702bc,NaN
33,B-FM321,Financieel management,b1de2a03-806e-ee11-b6a1-001dd8d702bc,NaN
34,B-FM322,Financieel management,0bdf2a03-806e-ee11-b6a1-001dd8d702bc,NaN
35,B-FM330,Financieel management,8ed23ef1-7f6e-ee11-b6a1-001dd8d702bc,NaN
36,B-FM340,Financieel management,f38664cd-7f6e-ee11-b6a1-001dd8d702bc,NaN
37,B-FM350,Financieel management,f037979d-7f6e-ee11-b6a1-001dd8d702bc,NaN
38,B-FM360,Financieel management,48508da9-7f6e-ee11-b6a1-001dd8d702bc,NaN
39,B-FM370,Financieel management,349a79bb-7f6e-ee11-b6a1-001dd8d702bc,NaN
40,B-FM410,Financieel management,246f55d9-7f6e-ee11-b6a1-001dd8d702bc,NaN
41,B-FM420,Financieel management,c7683feb-7f6e-ee11-b6a1-001dd8d702bc,NaN
42,B-FM430,Financieel management,4716a391-7f6e-ee11-b6a1-001dd8d702bc,NaN
43,B-FM440,Financieel management,6b39979d-7f6e-ee11-b6a1-001dd8d702bc,NaN
44,BI010,BIBOB,74167eb5-7f6e-ee11-b6a1-001dd8d702bc,NaN
45,B-IA020,Industriële automatisering,aad33ef1-7f6e-ee11-b6a1-001dd8d702bc,NaN
46,B-IN200,Interactie tussen OG en ON,f5b89b97-7f6e-ee11-b6a1-001dd8d702bc,NaN
47,B-IN220,Interactie tussen OG en ON,0c137eb5-7f6e-ee11-b6a1-001dd8d702bc,NaN
48,B-IN230,Interactie tussen OG en ON,75b272c1-7f6e-ee11-b6a1-001dd8d702bc,NaN
49,B-IN440,Interactie tussen OG en ON,427b30fd-7f6e-ee11-b6a1-001dd8d702bc,NaN