In [33]:
import json

from src.ingestion.relatics_client import RelaticsClient
from src.ingestion.xml_parser import parse_xml

In [34]:
# load configuration
with open(
    "configuration.json",
    "r",
    encoding="utf-8"
) as file:
    configuration = json.load(file)

In [35]:
# set element
elements = {
    "eis": "4dfa1495-7a2f-e911-a2d5-00155d641103"
    # "ontwerpprincipe": "b95be017-7a8d-ec11-b687-001dd8d702bc"
}

element = elements["eis"]

In [36]:
# get data
client = RelaticsClient(
    client_id=configuration["client_id"],
    client_secret=configuration["client_secret"],
    environment=configuration["environment"]
)

# configuration of ref for Eis
parameters = {
    "ConfigurationOfRef": element
}

root = client.get_request(
    workspace_id="210b2918-b359-4892-a23b-bf96ad23d82f",
    operation="dip_data_model_3",
    parameters=parameters
)

In [57]:
table = "Relations"

In [58]:
# element df 
df = parse_xml(
    root=root,
    report_part=table
)

print(df.shape)

df.head()

(51, 5)

,Relation,Cardinality,RelationID,R2Element,R2ElementID
0,[WEG] Heeft,0:n,70d4bcc7-f731-e911-a2d5-00155d641103,[WEG] Commentaar OG,bd935484-852f-e911-a2d5-00155d641103
1,[WEG] Heeft,1:1,2b36157b-0239-e911-a2d7-00155d641104,[WEG] Interpretatie OG,e7966525-0239-e911-a2d7-00155d641104
2,[WEG] Heeft property,0:1,28e40114-69d5-ea11-a2f0-00155d641104,[WEG] SRA status ON,7a4ae8fe-68d5-ea11-a2f0-00155d641104
3,[WEG] Heeft property,0:1,caf5f4e1-68d5-ea11-a2f0-00155d641104,[WEG] SMART-analyse OG,3d39b0b0-68d5-ea11-a2f0-00155d641104
4,[WEG] Heeft voorgestelde,0:1,75edf1cc-7754-e911-a2d8-00155d641103,[WEG] Commentaar OG,bd935484-852f-e911-a2d5-00155d641103

In [63]:
df['ChildR2Element'] = ''
df['ChildR2ElementID'] = ''
df

,Relation,Cardinality,RelationID,R2Element,R2ElementID,ChildR2Element,ChildR2ElementID
0,[WEG] Heeft,0:n,70d4bcc7-f731-e911-a2d5-00155d641103,[WEG] Commentaar OG,bd935484-852f-e911-a2d5-00155d641103,,
1,[WEG] Heeft,1:1,2b36157b-0239-e911-a2d7-00155d641104,[WEG] Interpretatie OG,e7966525-0239-e911-a2d7-00155d641104,,
2,[WEG] Heeft property,0:1,28e40114-69d5-ea11-a2f0-00155d641104,[WEG] SRA status ON,7a4ae8fe-68d5-ea11-a2f0-00155d641104,,
3,[WEG] Heeft property,0:1,caf5f4e1-68d5-ea11-a2f0-00155d641104,[WEG] SMART-analyse OG,3d39b0b0-68d5-ea11-a2f0-00155d641104,,
4,[WEG] Heeft voorgestelde,0:1,75edf1cc-7754-e911-a2d8-00155d641103,[WEG] Commentaar OG,bd935484-852f-e911-a2d5-00155d641103,,
5,Bevat (S),0:n,1731cf9e-0239-e911-a2d7-00155d641104,Eis,4dfa1495-7a2f-e911-a2d5-00155d641103,,
6,Heeft,0:1,e1ecc874-0759-ee11-b6a0-001dd8d702bf,Honorering,2d821dd9-0259-ee11-b6a0-001dd8d702bf,,
7,Heeft,0:n,1a160899-b699-ea11-a2ec-00155d641103,Toelichting,ae962581-b699-ea11-a2ec-00155d641103,,
8,Heeft,0:n,73d4bcc7-f731-e911-a2d5-00155d641103,Commentaar,275a8d8a-852f-e911-a2d5-00155d641103,,
9,Heeft,0:n,924d97e4-f731-e911-a2d5-00155d641103,Verificatievoorschrift,7be9db74-892f-e911-a2d5-00155d641103,,
10,Heeft,0:n,a04f7a89-e69b-e911-a2df-00155d641103,Gezamenlijke toelichting ON,eff6f051-e69b-e911-a2df-00155d641103,,
11,Heeft,0:n,dbedf7db-f731-e911-a2d5-00155d641103,[WEG] Verificatiecommentaar OG,37be0968-892f-e911-a2d5-00155d641103,,
12,Heeft,0:n,e0045d83-e69b-e911-a2df-00155d641103,Gezamenlijke toelichting OG,74cdf44a-e69b-e911-a2df-00155d641103,,
13,Heeft,1:1,2836157b-0239-e911-a2d7-00155d641104,Interpretatie ON,5046ad2b-0239-e911-a2d7-00155d641104,,
14,Heeft,1:1,877b33d5-f731-e911-a2d5-00155d641103,Project Activiteit,7efa7ec2-7a2f-e911-a2d5-00155d641103,,
15,Heeft,1:n,a06a34ce-f731-e911-a2d5-00155d641103,Eistekst,1979f387-862f-e911-a2d5-00155d641103,,
16,Heeft (C),0:n,8ef67718-59b9-eb11-b678-001dd8d702bc,Eis,4dfa1495-7a2f-e911-a2d5-00155d641103,,
17,Heeft betrekking op,0:n,7cc6e1a5-5af4-ef11-b6be-001dd8d702bf,GRIP Item,026357e7-48f4-ef11-b6be-001dd8d702bf,,
18,Heeft betrekking op,0:n,8becad86-f731-e911-a2d5-00155d641103,Aspect,892943cc-9b2e-e911-a2d5-00155d641103,,
19,Heeft betrekking op,0:n,c2376eb1-f731-e911-a2d5-00155d641103,Technologie/Principe,25a6f138-892f-e911-a2d5-00155d641103,,
20,Heeft betrekking op Activiteit,0:n,fa588c88-f931-e911-a2d5-00155d641103,ME-Eis-Activiteit,79aa8f8f-862f-e911-a2d5-00155d641103,,
21,Heeft betrekking op Bedrijfsproces,0:n,6ba4b8d6-148f-ec11-b687-001dd8d702bc,ME-Eis-Bedrijfsproces,d0e1e0ab-148f-ec11-b687-001dd8d702bc,,
22,Heeft betrekking op EOS Apparaat,0:n,8bf0914f-1e04-ec11-b67d-001dd8d702bc,ME-Eis-EOS apparaat,de60ade4-1d04-ec11-b67d-001dd8d702bc,,
23,Heeft betrekking op SBS,0:n,f6588c88-f931-e911-a2d5-00155d641103,ME-Eis-SBS,32b16920-832f-e911-a2d5-00155d641103,,
24,Heeft betrekking op SBS Contract,0:n,7e073d44-7637-ef11-b6ae-001dd8d702bf,ME-Eis-SBS Contract,c5cfa4b7-95f9-43f1-841d-f58e00c8cd5a,,
25,Heeft betrekking op SBS Type,0:n,b121dda7-77c1-ec11-b689-001dd8d702bf,ME-Eis-SBS type,5371c67e-77c1-ec11-b689-001dd8d702bf,,
26,Heeft contactpersoon,0:1,79a4f66f-efa6-e911-a2df-00155d641103,Rol,48e2234a-9b2e-e911-a2d5-00155d641103,,
27,Heeft eigenaar,0:n,d8af7d26-f931-e911-a2d5-00155d641103,Rol,48e2234a-9b2e-e911-a2d5-00155d641103,,
28,Heeft property,0:1,108e6382-9747-f011-b6c2-001dd8d702bc,SRA Thema,fe4a0331-9547-f011-b6c2-001dd8d702bc,,
29,Heeft property,0:1,25e40114-69d5-ea11-a2f0-00155d641104,SMART-analyse,9dc8ef06-69d5-ea11-a2f0-00155d641104,,
30,Heeft property,0:1,44b531ee-9aae-ec11-b688-001dd8d702bf,Type,fa7e60d4-9aae-ec11-b688-001dd8d702bf,,
31,Heeft property,0:1,458f8a61-75f5-e911-a2e5-00155d641104,Geldig tot en met,2ecb4ecc-d1f4-e911-a2e5-00155d641104,,
32,Heeft property,0:1,488f8a61-75f5-e911-a2e5-00155d641104,Geldig vanaf,8f4ecdda-d1f4-e911-a2e5-00155d641104,,
33,Heeft property,0:1,8b045c3a-75f5-e911-a2e5-00155d641104,RI&E opvolging,34ac2ae8-d1f4-e911-a2e5-00155d641104,,
34,Heeft property,0:1,a68e3dcd-f092-eb11-b674-001dd8d702bc,EMVI kans,93790c78-f092-eb11-b674-001dd8d702bc,,
35,Heeft property,0:1,ab8e3dcd-f092-eb11-b674-001dd8d702bc,Financieel risico,7860baa1-f092-eb11-b674-001dd8d702bc,,
36,Heeft property,0:1,c98e3dcd-f092-eb11-b674-001dd8d702bc,Kans,2960baa1-f092-eb11-b674-001dd8d702bc,,
37,Heeft property,0:1,d28e3dcd-f092-eb11-b674-001dd8d702bc,Risico,df58619a-f092-eb11-b674-001dd8d702bc,,
38,Heeft property,0:1,ee82d201-0759-ee11-b6a0-001dd8d702bf,Thema,c36b197e-0259-ee11-b6a0-001dd8d702bf,,
39,Heeft property,0:1,f8afd577-ff12-f111-b6cd-001dd8d702bf,Contractfase,5e06a84f-ff12-f111-b6cd-001dd8d702bf,,
40,Heeft property,0:1,fe161de8-68d5-ea11-a2f0-00155d641104,SRA status,8c35dcb7-68d5-ea11-a2f0-00155d641104,,
41,Heeft property,0:1|1,04171de8-68d5-ea11-a2f0-00155d641104,Status,fb1e21be-68d5-ea11-a2f0-00155d641104,,
42,Heeft property,0:1|1,83194cdb-68d5-ea11-a2f0-00155d641104,Geaccepteerd door ON,70b59d6a-68d5-ea11-a2f0-00155d641104,,
43,Heeft voorgestelde,0:n,49fc8e7a-f831-e911-a2d5-00155d641103,ME-Eis-Discipline mutatie,70dbef1c-862f-e911-a2d5-00155d641103,,
44,Is beschreven in,0:n,2033ca8e-f831-e911-a2d5-00155d641103,Document,b940cb29-7a2f-e911-a2d5-00155d641103,,
45,Is geinitieerd door,0:1,796a34bb-f831-e911-a2d5-00155d641103,Bedrijf,c1fe1b6a-9b2e-e911-a2d5-00155d641103,,
46,Is geinitieerd door,0:1,851831a6-309b-ee11-b6a6-001dd8d702bf,Persoon,fb5daf56-9b2e-e911-a2d5-00155d641103,,
47,Is van type,0:n,aea5f7a4-f831-e911-a2d5-00155d641103,Eis onderwerp,0e33f280-862f-e911-a2d5-00155d641103,,
48,Leidt tot,0:n,90db2205-e5ae-e911-a2df-00155d641103,Issue,315f53aa-7b2f-e911-a2d5-00155d641103,,
49,Resulteert in,0:n,8aa9d278-3eca-e911-a2e4-00155d641104,Ontwerp besluit,69bcbc50-39ca-e911-a2e4-00155d641104,,
50,Wordt uitgevoerd door,0:n,d4ca6056-57bd-eb11-b679-001dd8d702bf,WieDoetWat,9bc9c835-e2a0-ea11-a2ed-00155d641104,,

In [64]:
# set number of rows
table_length = 50

# file name
file_name = table

# set path
path = f"tests/unit/fixtures/test_transformer/{file_name}.parquet"

# export to parquet
df.to_parquet(path)